services:
  - type: web
    name: marche-api
    env: node
    plan: standard
    buildCommand: npm ci && npm run db:generate && npm run build -w @marche/db && npm run build -w @marche/api
    startCommand: npm run start -w @marche/api
    rootDir: apps/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
